name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun lint
      - run: bun test
      - run: bun export
      - run: bunx publint --strict
      - run: npm pack --ignore-scripts
      - run: bunx @arethetypeswrong/cli --profile esm-only rmapi-js-*.tgz
